spring.application.name=stashFlow

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/stashflow}
spring.datasource.username=${DB_USERNAME:stashflow}
spring.datasource.password=${DB_PASSWORD:stashflow}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration